version: "3.8"

services:
  api-gateway:
    build: .
    container_name: voting-system-api-gateway
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
    networks:
      - app-net

networks:
  app-net:
    external: true
